#Init NTP-server service
---
- name: "{{ ntp_service_name }} service config on host"
  template:
    src: systemd/ntp.service.j2
    dest: "/etc/systemd/system/{{ ntp_service_name }}.service"
    backup: yes
  notify: "{{ ntp_service_name }} restart"
