#Init NTP-server service
---
- name: Create ntp service user
  user: name={{ ntp_user_name }} uid={{ ntp_user_uid }} comment="NTP-docker" state=present

- name: {{ ntp_service_name }} service config on host
  template:
    src: systemd/ntp.service.j2
    dest: "/etc/systemd/system/{{ ntp_service_name }}.service"
    backup: yes
  notify: {{ ntp_service_name }} restart