#Remove NTP-server service
---
- name: "Stop {{ ntp_service_name }}"
  service:
    name: "{{ ntp_service_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes

- name: "Remove /etc/systemd/system/{{ ntp_service_name }}.service"
  file:
    path: "/etc/systemd/system/{{ ntp_service_name }}.service"
    state: absent
  notify: "{{ ntp_service_name }} restart uninstall"
