---
- name: "{{ ntp_service_name }} restart"
  become: true
  shell: systemctl daemon-reload
  notify: "{{ ntp_service_name }} restart service"

- name: "{{ ntp_service_name }} restart service"
  become: true
  service:
    name: "{{ ntp_service_name }}"
    state: restarted
    enabled: yes
  notify: firewall-cmd add-port

- name: firewall-cmd add-port
  become: true
  shell: firewall-cmd --zone=public --permanent --add-port=123/udp
  notify: service firewalld reload

- name: "{{ ntp_service_name }} restart uninstall"
  become: true
  shell: systemctl daemon-reload
  notify: reset failed

- name: "reset failed"
  become: true
  service: systemctl reset-failed
  notify: firewall-cmd remove-port

- name: firewall-cmd remove-port
  become: true
  shell: firewall-cmd --zone=public --permanent --remove-port=123/udp
  notify: service firewalld reload

- name: service firewalld reload
  become: true
  shell: systemctl restart firewalld
